version: "3.9"

services:
  core-cache-api:
    build: .
    restart: always
    container_name: core-cache-api
    volumes:
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_URLS=https://0.0.0.0:5000
      - ASPNETCORE_HTTPS_PORT=5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/servercert.pfx