version: "3.9"

services:
  core-cache-api:
    build: .
    restart: always
    container_name: core-cache-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development