version: "3.9"

networks:
  core_cache_api_network:
    driver: bridge

services:
  redis:
    container_name: redis-core-cache
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - core_cache_api_network
  core-cache-api:
    build: .
    restart: always
    container_name: core-cache-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_HOST=redis:6379
    links:
      - redis
    depends_on:
      - redis
    networks:
      - core_cache_api_network